# Generated by Django 4.2 on 2023-04-23 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=2)),
                ('quantity', models.PositiveIntegerField()),
                ('unit', models.CharField(max_length=10)),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='crm.producttype')),
            ],
        ),
    ]
