# Generated by Django 4.2 on 2023-04-24 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_productunit_alter_clients_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'Город', 'verbose_name_plural': 'Города'},
        ),
        migrations.RenameField(
            model_name='city',
            old_name='city_name',
            new_name='name',
        ),
    ]
