# Generated by Django 4.2 on 2023-04-25 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_alter_city_options_rename_city_name_city_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='destination_address',
            field=models.CharField(default='true_address', max_length=100, verbose_name='Адрес доставки'),
            preserve_default=False,
        ),
    ]
