# Generated by Django 4.2 on 2023-04-25 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_orders_destination_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='orders',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Номер заказа'),
        ),
        migrations.CreateModel(
            name='ProductOrder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Номер заказа')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='crm.products', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.AlterField(
            model_name='orders',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='crm.productorder', verbose_name='Продукт'),
        ),
    ]
