# Generated by Django 4.2 on 2023-05-27 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_alter_productorder_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='telegram_user_id',
            field=models.CharField(default='tg_id', max_length=20, verbose_name='Телеграм user_id'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Город'),
        ),
    ]
