# Generated by Django 4.2 on 2023-06-10 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_clients_telegram_user_id_alter_city_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_user_id', models.CharField(max_length=20, verbose_name='Телеграм user_id')),
            ],
            options={
                'verbose_name': 'Telegram id для уведомлений',
                'verbose_name_plural': 'Telegram id для уведомлений',
            },
        ),
    ]
